# Generated by Django 2.0 on 2018-06-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_copo', '0002_repository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
