# Generated by Django 2.0 on 2018-06-26 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_copo', '0004_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='member_of',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), blank=True, size=None),
        ),
    ]
