# Generated by Django 2.0 on 2018-06-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_copo', '0006_auto_20180626_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='member_of',
            new_name='managed_repositories',
        ),
    ]
