# Generated by Django 2.0 on 2018-06-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_copo', '0007_auto_20180626_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
