# Generated by Django 3.1 on 2020-11-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_copo', '0002_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='publication',
        ),
    ]
