# Generated by Django 3.1 on 2020-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_copo', '0003_delete_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
            ],
        ),
    ]
