# Generated by Django 3.1 on 2020-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_copo', '0004_banner_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_view',
            name='body_txt',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='banner_view',
            name='header_txt',
            field=models.TextField(default='', max_length=100),
        ),
    ]
